### ISSUE TITLE
Angular SDK doesn't display social buttons

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-dotnet-owin-middleware#24]
The .NET backend is not sending the proper data to the frontend, so the Angular client is unable to render the social buttons correctly. See https://github.com/stormpath/stormpath-sdk-angularjs/issues/160

**Comment by maxbailey** [comment]
This would be awesome to get worked out. This is currently a blocking issue for an application that I'm working on. Thanks!

**Comment by Confusingboat** [comment]
Is there a reason this issue keeps getting pushed back?

**Comment by nbarbettini** [comment]
@Confusingboat No reason, other than release 2.0.0 being delayed longer than I anticipated. Thanks for your patience -- I will get to this as soon as possible!

**Comment by nbarbettini** [comment]
Made progress today in https://github.com/stormpath/stormpath-dotnet-owin-middleware/commit/bca5014b2bc791e4dc80d1e902223fbd92c620ed. Still needs testing, though - that'll be next on the list.

**Comment by nbarbettini** [comment]
This has been fixed and merged for [release 2.1.0](https://github.com/stormpath/stormpath-dotnet-owin-middleware/milestone/7). It's currently available (in prerelease) on MyGet: https://www.myget.org/feed/Packages/stormpath-owin
