### ISSUE TITLE
Support for swagger

### ISSUE THREAD

**Issue by Doug-Shannon** [stormpath/stormpath-dotnet-owin-middleware#39]
I would love to see an implementation that plays nice with [swagger](http://swagger.io/) and [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle).  Right there is not an easy way to setup cookie auth and the runtime generated stormpath endpoints do not show up in the swagger ui.

**Comment by nbarbettini** [comment]
Unfortunately I wasn't able to get this done before the acquisition of Stormpath by Okta. Sorry! ☹️ I'll definitely keep swagger/swashbuckle in mind for future Okta stuff.

**Comment by Tibincrunch** [comment]
No problem, good luck at Okta!

**Comment by nbarbettini** [comment]
Thanks @Tibincrunch! 😄
