### ISSUE TITLE
Logout refreshes an expired token/cookie, doesn't log user out.

### ISSUE THREAD

**Issue by shelly-skeens** [stormpath/stormpath-dotnet-owin-middleware#44]
In our .NET implementation, we are seeing that logout is actually refreshing a user's access token (and not logging out), if the user clicks logout any time after the token has expired.  This requires the user to hit logout again in order to actually log out.  If the token has not expired, logout works as expected.

**Comment by nbarbettini** [comment]
Thanks @shelly-skeens! I will take a look and update here.

**Comment by nbarbettini** [comment]
Fixed in 3862ece and slated for release 3.1.0.

**Comment by shelly-skeens** [comment]
Fantastic!  Thank you!
