### ISSUE TITLE
Application fails to authenticate in Stormpath when API Key and Secret are NOT hardcoded.

### ISSUE THREAD

**Issue by ghost** [stormpath/stormpath-dotnet-owin-middleware#45]
This problem exists when building a .NET Core RTM WebAPI.

Following the instructions on the documentation site, I attempted both putting the API key and secret in an environment variable and in a stormpath.json and .yaml file at the root directory (not at the same time). In all cases, my application was unable to authenticate against the Stormpath API. Although, I should note any additional configurations in the .json/.yaml file were picked up and applied, so it's not a case of the not being found.
If I instead put the key and secret in the ConfigureServices method in Startup.cs during the `services.AddStormpath()` call, everything works as intended.

I originally talked to Michele Degges about this over the support ticket system and she confirmed my files were correctly formatted. We could only conclude that something must be up with my setup.

**Comment by diveboatslave** [comment]
I'm using environment variables and they're working ok for me, did you set the application href too?

**Comment by nbarbettini** [comment]
That does sound odd! Some quick thoughts:
- Environment variables are tricky on Windows. You have to restart Visual Studio at least, or sometimes the machine (to be safe) for them to "stick". Any chance that was why they weren't picked up?
- Can you post the YAML or JSON file you tried? It sounds like it might be a formatting issue. (If the SDK can't parse one or more sections of the config file, it'll ignore them silently)

**Comment by ghost** [comment]
Yes, I added the href of the application as well.
Before I recreate the files (I deleted them since the configurations i was testing against in them isn't needed, at least not right now), I should also note that I also tried downloading the apiKey.properties file and dumping that in the root directory (per https://docs.stormpath.com/dotnet/aspnetcore/latest/configuration.html) but that doesn't work either.
I checked for the .stormpath folder in %HOMEDRIVE%%HOMEPATH%%.stormpath but that folder hasn't been created (and honestly, not sure how to make that folder either as it prevents me from doing so). so those do not work for me as well.
i'll create the configuration file, test it again to make sure and post the file if it indeed still doesn't work.

**Comment by ghost** [comment]
well, look at that. the environment variable i originally set up was an old bad apikey. replaced it all with the latest correct values and it worked.
deleted them all, added the apiKey.properties file back at the root directory and it worked.
I'm guessing the .json file will work correctly now.
fascinating that the inline hardcode overrode everything.
but, it has been fixed.
thanks!

**Comment by nbarbettini** [comment]
Ah, makes sense! There's an order of inheritance to the configuration loading process: configuration supplied via code always wins, and environment variables are [second](https://github.com/stormpath/stormpath-dotnet-config/blob/master/src/Stormpath.Configuration/DefaultConfigurationLoader.cs#L77). That explains both why the bad env var was overriding your good JSON file, and why defining the credentials in code fixed it.

Glad it's working! 😄
