### ISSUE TITLE
Visual Studio Code launches wrong URL after adding Stormpath Middleware

### ISSUE THREAD

**Issue by leebrandt** [stormpath/stormpath-dotnet-owin-middleware#50]
After adding the Stormpath Owin Middleware, F5 to launch the app in VS Code launches https://localhost instead of http://localhost:5000

Just a little annoying to always have to change it by hand. but it is definitely still _running_ on localhost:5000.

**Comment by nbarbettini** [comment]
I'm pretty sure this is a VS Code bug, nothing to do with this package. Can you let me know if you can repro this in the latest version of VS Code @leebrandt?
