### ISSUE TITLE
Custom Views

### ISSUE THREAD

**Issue by Tibincrunch** [stormpath/stormpath-dotnet-owin-middleware#81]
I have a couple weird things happening with custom Views. I'm trying to replace the default Login View with my own and have specified the path in my Startup.cs per the [documentation](https://docs.stormpath.com/dotnet/aspnetcore/latest/templates.html#custom-views).

```
Login = new WebLoginRouteConfiguration()
{
    Enabled = true,
    View = "~/Views/Stormpath/Login.cshtml",
    Uri = "/Account/Login"
},
```

My custom View appears if I'm already logged in, otherwise I get a 502.3 Bad Gateway error. In the custom View I have the [same code](https://github.com/stormpath/stormpath-dotnet-owin-middleware/blob/master/src/Stormpath.Owin.Views/Views/Stormpath/Login.cshtml) from this repository, however I changed the button text to Log In Test.

I've also noticed that specifying just the View name "Login" does not work at all... the default View is used instead.

Finally, it seems that the Uri route is case sensitive. Navigating to /account/login returns a 404 Not Found result while /Account/Login returns correctly. I'm not sure if this behavior is intended.

I'm still new to Stormpath so forgive me if these issues stem from my naivety. Thanks!

**Comment by nbarbettini** [comment]
Closing in favor of https://github.com/stormpath/stormpath-aspnetcore/issues/40 😄
