### ISSUE TITLE
'HTTP request failure' returned if password does not meet complexity requirements

### ISSUE THREAD

**Issue by dnvnjstc** [stormpath/stormpath-dotnet-owin-middleware#95]
It would be nice if more descriptive error messages could be returned. 

For example, if user is registering and does not meet the password complexity requirements defined in Okta, it only returns the default 'HTTP request failure' error. Also occurs on password reset.

**Comment by nbarbettini** [comment]
I agree. I'll work on this for the next minor release.

**Comment by nbarbettini** [comment]
The improved behavior will ship with 4.1.0 -- see https://github.com/stormpath/stormpath-dotnet-owin-middleware/pull/97 for a detailed explanation.
