### ISSUE TITLE
Email verification token is no longer valid

### ISSUE THREAD

**Issue by dnvnjstc** [stormpath/stormpath-dotnet-owin-middleware#98]
The email verification flow is no longer working with Okta. 

We have implemented our own in-house handler to keep email verification a part of the registration process.  When a user has registered, we generate an email with the custom profile property `emailVerificationToken` set on the `sptoken` url parameter in the `/verify` path:

`https://www.website.com/verify?sptoken={emailVerificationToken}` 

When the user clicks on the verify link in the email, it always returns with the error "This verification link is no longer valid. Please request a new link from the form below." This would mean the `InvalidSpToken` property is always true for the `VerifyEmailFormViewModel`.

Our verification handler hasn't changed since we have migrated from Stormpath to Okta, so we believe that something has changed in Okta where the Stormpath Middleware can no longer search users based on the `emailVerificationToken` custom property and is capturing an exception.

**Comment by nbarbettini** [comment]
Hey @dnvnjstc - looking into this. Sorry for the issue. I'll have more info soon.

**Comment by nbarbettini** [comment]
This may have been due to a temporary outage. Are you still seeing this issue?

Feel free to email nate.barbettini@okta.com if you want to discuss further. Happy to help.

**Comment by nbarbettini** [comment]
Hey @dnvnjstc - are you still seeing this?

**Comment by dnvnjstc** [comment]
Hey @nbarbettini - my apologies.  Email verification is back to normal.  Thank you for investigating this.

**Comment by nbarbettini** [comment]
No problem. Glad everything's working. Sorry for the temporary interruption!
